# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adf3cb76bf061d9a33bb6c33d2f69c22dbb0a737ca7e04a66c0421c5a199da77a8cb0050f8335dd1199edb57bd6ed35cf8e7cb325b929d9bc2f6457749599ef2

test:
  secret_key_base: 7066ec73eee1181e458866d2a9ead21eb9f4cbe4bbe51e7e862f10fb127bfda986b2553e35fa460f5ab9b107196110e6d13a7d78c42adcb60c32a4d56bb0ffdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
